version: '3.8'

services:
  product-service:
    build: .
    container_name: electrozone-product-service
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=product-service-database
    depends_on:
      - db
    networks:
      - electrozone-network

  db:
    image: postgres:17
    container_name: electrozone-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-service-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - electrozone-network

volumes:
  postgres_data:

networks:
  electrozone-network:
    driver: bridge
